stages:
  - "deploy"

pages:
  stage: "deploy"
  script:
    - "echo 'Editor app will be available at: https://fwcc.pages.hzdr.de/data-management/forms-generator/'"
  artifacts:
    paths:
      - "public"
